App.Web.Mvc/Areas/Admin/Controllers/BlogController.cs
using App.Business.Dtos.Post;
using App.Business.Services.Abstract;
using App.Persistence.Data.Entity;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class BlogController : Controller
	{
		IPostService _postService;
		IMapper _mapper;
		public BlogController(IPostService postService, IMapper mapper)
		{
			_postService = postService;
			_mapper = mapper;
		}

		public IActionResult Index()
		{
			var posts = _postService.GetAllViewPostDtos();
			return View(posts);
		}

		//CREATE
		[HttpGet]
		public IActionResult Create()
		{
			var returnedDto = _postService.PopulatePostCategories(null);
			return View(returnedDto);
		}

		[HttpPost]
		public IActionResult Create(CreateOrEditPostDto postDto)
		{
			if (postDto == null) { return RedirectToAction("Index"); }
			var post = _mapper.Map<Post>(postDto);

			if (ModelState.IsValid)
			{
				_postService.Insert(post);
				_postService.SaveChanges();
				_postService.InsertCategoryPost(postDto.selectedCategoryIds, post);
				_postService.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(_postService.PopulatePostCategories(postDto));
		}

		//Edit
		[HttpGet]
		public IActionResult Edit(int id)
		{
			if (id == 0) { return RedirectToAction("Index"); }

			var post = _postService.GetById(id);

			if (post == null)
			{ return RedirectToAction("Index"); }

			var postDto = _mapper.Map<CreateOrEditPostDto>(post);

			var returnedDto = _postService.PopulatePostCategories(postDto);
			returnedDto.selectedCategoryIds = _postService.GetSelectedCategoryIds(post.Id);
			return View(returnedDto);
		}

		[HttpPost]
		public IActionResult Edit(CreateOrEditPostDto postDto)
		{
			if (postDto == null) { return RedirectToAction("Index"); }
			var post = _mapper.Map<Post>(postDto);

			if (ModelState.IsValid)
			{
				_postService.Update(post);
				_postService.SaveChanges();
				_postService.UpdateCategoryPost(postDto.selectedCategoryIds, post);
				_postService.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(_postService.PopulatePostCategories(postDto));
		}

		//DELETE
		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (id == 0) { return RedirectToAction("Index"); }

			var post = _postService.GetById(id);

			if (post == null)
			{ return RedirectToAction("Index"); }

			return View(post);
		}


		[HttpPost, ActionName("Delete")]
		public IActionResult DeletePost(int id)
		{
			if (id == 0) { return RedirectToAction("Index"); }

			_postService.DeleteById(id);
			_postService.SaveChanges();
			return RedirectToAction("Index");

		}
	}
}

App.Web.Mvc/Areas/Admin/Controllers/PostCommentController.cs
using App.Business.Dtos.PostComment;
using App.Business.Services.Abstract;
using App.Persistence.Data.Entity;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
namespace App.Web.Mvc.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class PostCommentController : Controller
	{
		IPostCommentService _postCommentService;
		IMapper _mapper;
		public PostCommentController(IPostCommentService postCommentService, IMapper mapper)
		{
			_postCommentService = postCommentService;
			_mapper = mapper;
		}
		public IActionResult Index(int id)
		{
			var comments = _postCommentService.GetAllByPostId(id);
			TempData["postId"] = id;
			return View(comments);
		}
		//CREATE
		[HttpGet]
		public IActionResult Create(int id)
		{
			TempData["postId"] = id;
			PostCommentCreateOrEditDto postComment = new PostCommentCreateOrEditDto() { PostId = id };
			return View(postComment);
		}
		[HttpPost]
		public IActionResult Create(PostCommentCreateOrEditDto postCommentDto)
		{
			if (postCommentDto == null) { return RedirectToAction("Index", new { id = postCommentDto.PostId }); }
			var postComment = _mapper.Map<PostComment>(postCommentDto);
			postComment.Id = 0;
			if (ModelState.IsValid)
			{
				_postCommentService.Insert(postComment);
				_postCommentService.SaveChanges();
				return RedirectToAction("Index", new { id = postCommentDto.PostId });
			}
			return View(postCommentDto);
		}
		//EDIT
		[HttpGet]
		public IActionResult Edit(int id)
		{
			/*TempData["postId"] = id;*/
			var comment = _postCommentService.GetById(id);
			var postCommentDto = _mapper.Map<PostCommentCreateOrEditDto>(comment);
			return View(postCommentDto);
		}
		[HttpPost]
		public IActionResult Edit(PostCommentCreateOrEditDto postCommentDto)
		{
			if (postCommentDto == null) { return RedirectToAction("Index", new { id = postCommentDto.PostId }); }
			var postComment = _mapper.Map<PostComment>(postCommentDto);
			if (ModelState.IsValid)
			{
				_postCommentService.Update(postComment);
				_postCommentService.SaveChanges();
				return RedirectToAction("Index", new { id = postCommentDto.PostId });
			}
			return View(postCommentDto);
		}
		//DELETE
		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (id == 0) { return RedirectToAction("Index"); }
			var postComment = _postCommentService.GetById(id);
			TempData["postId"] = postComment.PostId;
			if (postComment == null)
			{ return RedirectToAction("Index"); }
			return View(postComment);
		}
		[HttpPost]
		public IActionResult Delete(PostComment postComment)
		{
			if (postComment == null) { return RedirectToAction("Index"); }
			_postCommentService.DeleteById(postComment.Id);
			_postCommentService.SaveChanges();
			return RedirectToAction("Index", new { id = TempData["postId"] });
		}
	}
}

App.Web.Mvc/Areas/Admin/Controllers/PostImageController.cs
using App.Business.Services.Abstract;
using App.Persistence.Data.Entity;
using Microsoft.AspNetCore.Mvc;
namespace App.Web.Mvc.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class PostImageController : Controller
	{
		IPostImageService _postImageService;
		public PostImageController(IPostImageService postImageService)
		{
			_postImageService = postImageService;
		}
		public IActionResult Index(int id)
		{
			var postImage = _postImageService.GetByPostId(id);
			TempData["postId"] = id;
			if (postImage == null)
			{
				var newPI = new PostImage();
				newPI.ImageUrl = "";
				return View(newPI);
			}
			return View(postImage);
		}
		//CREATE
		[HttpGet]
		public IActionResult Create(int id)
		{
			var postImage = new PostImage { PostId = id };
			TempData["postId"] = id;
			return View(postImage);
		}
		[HttpPost]
		public ActionResult Create(PostImage model)
		{
			if (model.Image != null)
			{
				string directoryPath = "wwwroot/images/slider";
				Directory.CreateDirectory(directoryPath);
				string filePath = Path.Combine(directoryPath, model.Image.FileName);
				if (Path.Exists(filePath) == false)
				{
					using var stream = System.IO.File.Create(filePath);
					model.Image.CopyTo(stream);
				}
				model.Id = 0;
				model.ImageUrl = filePath.Replace("wwwroot", "..");
				_postImageService.Insert(model);
				_postImageService.SaveChanges();
				return RedirectToAction("Index", new { id = model.PostId });
			}
			return View(model);
		}
		//EDIT
		[HttpGet]
		public IActionResult Edit(int id)
		{
			TempData["postId"] = id;
			var postImage = _postImageService.GetByPostId(id);
			if (postImage != null)
				return View(postImage);
			var postImageNew = new PostImage { PostId = id };
			return View(postImageNew);
		}
		[HttpPost]
		public ActionResult Edit(PostImage model)
		{
			var modelToChange = _postImageService.GetByPostId(model.PostId);
			if (model.Image != null)
			{
				string directoryPath = "wwwroot/images/slider";
				Directory.CreateDirectory(directoryPath);
				string filePath = Path.Combine(directoryPath, model.Image.FileName);
				if (Path.Exists(filePath) == false)
				{
					using var stream = System.IO.File.Create(filePath);
					model.Image.CopyTo(stream);
				}
				modelToChange.ImageUrl = filePath.Replace("wwwroot", "..");
				_postImageService.Update(modelToChange);
				_postImageService.SaveChanges();
				return RedirectToAction("Index", new { id = model.PostId });
			}
			return View(model);
		}
		//EDIT
		[HttpGet]
		public IActionResult Delete(int id)
		{
			TempData["postId"] = id;
			var postImage = _postImageService.GetByPostId(id);
			if (postImage != null)
				return View(postImage);
			var postImageNew = new PostImage { PostId = id };
			return View(postImageNew);
		}
		[HttpPost]
		public ActionResult Delete(PostImage model)
		{
			var modelToDelete = _postImageService.GetByPostId(model.PostId);
			_postImageService.DeleteById(modelToDelete.Id);
			_postImageService.SaveChanges();
			return RedirectToAction("Index", new { id = model.PostId });
		}
	}
}

App.Web.Mvc/Controllers/BlogController.cs
using App.Business.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
	public class BlogController : Controller
	{
		private readonly IPostService _postService;

		public BlogController(IPostService postService)
		{

			_postService = postService;
		}

		public IActionResult Search(string query, int page)
		{
			return View();
		}
		[Route("/blog/title-slug")]
		public IActionResult Detail(int id)
		{
			if (id == 0)
				return RedirectToAction(nameof(Index));

			var post = _postService.GetById(id);
			if (post is null)
				return RedirectToAction(nameof(Index));

			ViewBag.CategoryName = _postService.GetCategoryName(id);
			return View(post);

		}
	}
}

App.Web.Mvc/Areas/Admin/Views/Blog/Create.cshtml
@model App.Business.Dtos.Post.CreateOrEditPostDto

<div class="container">

	<div class="row mb-2">
		<div class="col">
			<div class="card">
				<div class="card-header">
					<h5>Gönderi Oluştur</h5>
					@*<div asp-validation-summary="All"></div>*@
				</div>
				<div class="card-body">
					<form asp-controller="Blog" asp-action="Create" method="post" class="d-flex align-items-center">
						<div class="container">

							<div class="row mb-4">
								<div class="col">
									<label asp-for="PostTitle" class="mb-2"></label>
									<input type="text" asp-for="PostTitle" class="form-control" placeholder="Ad" />
									<span asp-validation-for="PostTitle" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-4">
								<div class="col">
									<label asp-for="PostContext" class="mb-2"></label>
									<textarea asp-for="PostContext" class="form-control" placeholder="Tanım"></textarea>
									<span asp-validation-for="PostContext" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-4">
								<div class="col">
									<label class="control-label mb-2" asp-for="selectedCategoryIds"></label>
									<select asp-for="selectedCategoryIds" multiple="multiple" class="form-control" asp-items="@(new MultiSelectList(Model.Categories, "Id", "CategoryName", Model.selectedCategoryIds))">
										@*<option value="">-- Kategori Seç --</option>*@
									</select>
									<span asp-validation-for="selectedCategoryIds" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-2">
								<div class="col">
									<button type="submit" class="btn btn-warning" style="width:150px">Oluştur</button>
									<a asp-controller="Blog" asp-action="Index" class="btn btn-primary" style="width:150px">Listeye Dön</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

App.Web.Mvc/Areas/Admin/Views/Blog/Delete.cshtml
@model App.Persistence.Data.Entity.Post

<div class="container">
	<div class="row mb-2">
		<div class="col">
			<div class="card">
				<div class="card-header">
					<h5>Ürün Kategorisi Silme</h5>
					@*<div asp-validation-summary="All"></div>*@
				</div>
				<div class="card-body">
					<form asp-controller="Blog" asp-action="Delete" method="post" class="d-flex align-items-center">
						<div class="container">

							<div class="row mb-4">
								<div class="col">
									<label asp-for="Title" class="mb-2"></label>
									<div class="container bg-secondary text-white rounded p-2">@Model.Title</div>
								</div>
							</div>
							<div class="row mb-4">
								<div class="col">
									<label asp-for="Context" class="mb-2"></label>
									<div class="container bg-secondary text-white rounded p-2">@Model.Context</div>
								</div>
							</div>
							<div class="row mb-2">
								<div class="col">
									<button type="submit" class="btn btn-danger" style="width:150px">Sil</button>
									<a asp-controller="Blog" asp-action="Index" class="btn btn-primary" style="width:150px">Listeye Dön</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

App.Web.Mvc/Areas/Admin/Views/Blog/Edit.cshtml
@model App.Business.Dtos.Post.CreateOrEditPostDto

<div class="container">

	<div class="row mb-2">
		<div class="col">
			<div class="card">
				<div class="card-header">
					<h5>Gönderi Değiştir</h5>
					@*<div asp-validation-summary="All"></div>*@
				</div>
				<div class="card-body">
					<form asp-controller="Blog" asp-action="Edit" method="post" class="d-flex align-items-center">
						<div class="container">

							<div class="row mb-4">
								<div class="col">
									<label asp-for="PostTitle" class="mb-2"></label>
									<input type="text" asp-for="PostTitle" class="form-control" placeholder="Ad" />
									<span asp-validation-for="PostTitle" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-4">
								<div class="col">
									<label asp-for="PostContext" class="mb-2"></label>
									<textarea asp-for="PostContext" class="form-control" placeholder="Tanım"></textarea>
									<span asp-validation-for="PostContext" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-4">
								<div class="col">
									<label class="control-label mb-2" asp-for="selectedCategoryIds"></label>
									<select asp-for="selectedCategoryIds" multiple="multiple" class="form-control" asp-items="@(new MultiSelectList(Model.Categories, "Id", "CategoryName", Model.selectedCategoryIds))">
										@*<option value="">-- Kategori Seç --</option>*@
									</select>
									<span asp-validation-for="selectedCategoryIds" class="text-danger"></span>
								</div>
							</div>

							<div class="row mb-2">
								<div class="col">
									<button type="submit" class="btn btn-warning" style="width:150px">Değiştir</button>
									<a asp-controller="Blog" asp-action="Index" class="btn btn-primary" style="width:150px">Listeye Dön</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

App.Web.Mvc/Areas/Admin/Views/Blog/Index.cshtml
@model IEnumerable<App.Business.Dtos.Post.ViewPostDto>
@{
	ViewData["Title"] = "Blog Admin Page";
}
<div class="container">
	<div class="row mb-2">
		<div class="col">
			<a class="btn btn-primary" asp-controller="Blog" asp-action="Create"><i class="bi-plus-circle"></i> Yeni Gönderi Ekle</a>
		</div>
	</div>
	<div class="row mb-2">
		<div class="col">
			<div class="card">
				<div class="card-header">
					<h5>Gönderi Listesi</h5>
				</div>
				<div class="card-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">Değiştir/Sil/Post Yorumları/Post Resimleri</th>
								<th scope="col"><label asp-for="@Model.FirstOrDefault().PostTitle ?? " Gönderi Başlığı""></label></th>
								<th scope="col"><label asp-for="@Model.FirstOrDefault().PostContext ?? " Gönderi İçeriği""></label></th>
								<th scope="col"> Kategori Adı</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var (item, i) in Model.Select((item, i) => (item, i)))
							{
								<tr>
									<th scope="row">@(i + 1)</th>
									<th>
										<a class="m-1" asp-controller="Blog" asp-action="Edit" asp-route-id="@item.Id"><i class="bi-pencil-square text-success"></i></a>
										<a class="m-1" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.Id"><i class="bi-trash text-danger"></i></a>
										<a class="m-1" asp-controller="PostComment" asp-action="Index" asp-route-id="@item.Id"><i class="bi-chat-square-dots text-warning"></i></a>
										<a class="m-1" asp-controller="PostImage" asp-action="Index" asp-route-id="@item.Id"><i class="bi-file-earmark-image text-secondary"></i></a>
									</th>
									<td>@item.PostTitle</td>
									<td>@item.PostContext</td>
									<td>
										@if (item.CategoryPosts != null)
										{
											@String.Join(", ", item.CategoryPosts.Select(p => p.Category.Name).ToArray())
										}
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>